# Generated by Django 2.2.3 on 2019-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(max_length=50, unique=True)),
                ('to_location', models.CharField(max_length=150)),
                ('from_location', models.CharField(max_length=150)),
                ('departure_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('departure_date',),
            },
        ),
    ]
