# Generated by Django 2.2.3 on 2019-07-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
