# Generated by Django 2.2.3 on 2019-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class', models.CharField(choices=[('BS', 'Business'), ('FR', 'First'), ('EC', 'Economy')], default='BS', max_length=2)),
                ('cost', models.IntegerField(default=0)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
