# Generated by Django 2.2.3 on 2019-07-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_last_login'),
        ('ticket', '0004_auto_20190719_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
        migrations.AddField(
            model_name='ticket',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to='account.User'),
        ),
    ]
